<a href="https://colab.research.google.com/github/JossRoss04/JossRoss04.github.io/blob/main/mineriaDeDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Míneria de Datos

## Primer parcial

### Introducción

#### Conceptos

**Mineria de Datos:** Es la recolección de datos implementando distintas estrategias y herramientas con el fin de excarvar sus patrones, llevandolas al analisis para la predicción y descripción de información.

#### Ciencia de Datos

In [ ]:
# La función help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
# Otra forma de obtener ayuda es utilizando el caracter ?
len?

In [ ]:
# Así creamos una lista
L = [1, 2, 3]

In [ ]:
L.insert?

In [ ]:
L?

Object `L` not found.


In [ ]:
 # Ejemplo con una función con Docstring
 def square(a):
  """Return the square of a."""
  return a ** 2



In [ ]:
square(5)

25

####IPython Magic Commands

#####Timing Code Execution:

In [ ]:
#Sirve para evaluar el desempeño de una expresión en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

The slowest run took 4.90 times longer than the fastest. This could mean that an intermediate result is being cached.
122 µs ± 88.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#Con doble % podemos evaluar el desempeño de multiples lineas
%%timeit
L=[]
for n in range(1000):
  L.append(n**2)

93.8 µs ± 27 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
!ls

sample_data


In [ ]:
!pwd

/content


In [ ]:
!echo

In [ ]:
directory = !pwd

In [ ]:
print(directory)

['/content']


In [ ]:
%cd /content/

/content


In [ ]:
%ls

sample_data/


####Understanding Data Types in Python

In [2]:
import numpy as np

In [ ]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([3.14, 4, 2, 3], dtype='float32')

array([3.14, 4.  , 2.  , 3.  ], dtype=float32)

In [ ]:
np.array([3.14, 4, 2, 3], dtype='int')

array([3, 4, 2, 3])

In [ ]:
# Cuando el argumento de np.array es una iteración anidada
# genera una matriz
np.array([range(i, i+3) for i in (2, 4, 6)])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
[range(i, i+3) for i in [2, 3, 4]]


[range(2, 5), range(3, 6), range(4, 7)]

In [3]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [4]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
np.random.random((3,3))

array([[0.29157051, 0.82690341, 0.77461723],
       [0.70308866, 0.18499014, 0.84411985],
       [0.20195221, 0.25831772, 0.87055555]])

In [47]:
np.random.normal(0,1,5)

array([ 0.26989104,  1.46632864,  1.35695615,  0.04750682, -0.94516444])

In [54]:
np.random.randint(0, 4, (3,3))

array([[3, 1, 3],
       [2, 2, 2],
       [0, 3, 2]])

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
np.empty(3)

array([1., 1., 1.])

####The Basics of NumPy Arrays

In [57]:
np.random.seed(0)
x1 = np.random.randint(10, size=6) #One-dimensional array
x2 = np.random.randint(10, size=(3,4)) #Two-dimensional array
x3 = np.random.randint(10, size=(3,4,5)) #Three-dimensional array

In [59]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [60]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


#####Array Indexing: Accessing Single Elements

In [61]:
x1

array([5, 0, 3, 3, 7, 9])

In [62]:
x1[0]

np.int64(5)

In [65]:
x1[-1]

np.int64(9)

In [67]:
x1[-2]

np.int64(7)

In [68]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [69]:
x2[0,2]

np.int64(2)

In [72]:
x2[0,0] = 12

####Promedio (Average) y Promedio Ponderado

In [74]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [75]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


####Mediana

In [78]:
mediana = np.median(data)
print(mediana)

3.0


####Varianza y desviacion estandar

In [79]:
varianza = np.var(data)
desviacion = np.std(data)

###Generación de Datos Aleatorios

In [84]:
muestra = np.random.normal(0,1,1000)
print(np.mean(muestra), np.std(muestra))

0.03583084515706754 1.0098457282707611


####Correlación

In [85]:
corr = np.corrcoef([1,2,3],[1,5,7])
print(corr)

[[1.         0.98198051]
 [0.98198051 1.        ]]
